Try №2 - tests+gitignore
bmkodoo/javacourses2016 pull request #3
Opened 2016-11-18 20:05 UTC by PutienkoEN

Task1Test Edit(added \n)
Task3Test Edit(added foreach + file route + changed data-source + added white space to poem)
Task4Test Added
Task6Test Added
Task7Test Added
Task19Test Added
Car class constructor changed from package-privte to public (for test)

2016-11-19 20:09 UTC, nkarulin requested changes
Спасибо!
- [ ] Нужно отключить все тесты (`@Test(enabled = false`), т.к. в мастере нет реализаций, а он падать не должен.
- [ ] .gitignore и вправду не должен быть в репозитории. Самый простой способ его убрать, это [сделать коммит с удалением файла](http://stackoverflow.com/questions/7927230/remove-directory-from-remote-repository-after-adding-them-to-gitignore). К слову, в .gitignore следует добавить .gitignore:)
- [ ] Make github happy and add line at the end of file

Обращайте внимание на checks, shippable должен быть пройден, если это не так (как, например, сейчас), то можно нажать Details и посмотреть, почему билд падает.

2016-11-19 20:09 UTC, nkarulin commented on src/test/java/com/epam/javacourses2016/task19/SolverTask19Test.java
> +        Assert.assertEquals(solver.getNumberOvertaking(cars,lengthLap,numberLaps), overtake);
Пробельчики

2016-11-19 20:09 UTC, nkarulin commented on src/test/java/com/epam/javacourses2016/task19/SolverTask19Test.java
> +                }},
Может быть вместо инстанцирование мапы в dataProvider, передавать в тест массив, а уже в тесте создвать на его основе множество?

2016-11-19 20:09 UTC, nkarulin commented on src/test/java/com/epam/javacourses2016/task6/SolverTask6Test.java
> +                        }},
Здесь тоже кажется, что простого массива целочисленных будет достаточно для задания полинома? Тест кейсы тогда бы гораздо легче читались

2016-11-19 20:09 UTC, nkarulin commented on src/test/java/com/epam/javacourses2016/task7/SolverTask7Test.java
> +                            add(0, 8);
В этих тесткейсах простого массива примитивов точно будет достаточно, а ArrayList пускай формируется на их основе перед передачей в солвер

2016-11-20 11:43 UTC, PutienkoEN commented
Тесты отключил, теперь проходит проверка(а я думал что там за медалька такая... а то оказывается он проверку делал =))
Гитигнор убрал.
Data provider поменял все на массивы, сделал методы для "сборки" коллекций.
Добавил еще несколько тестов.

Мне теперь по новой надо как-то пулл-реквест сделать или он автоматом изменения подцепляет(ветку я запушил)? Не вижу кнопки "отправить повторно".

2016-11-20 19:24 UTC, nkarulin approved these changes

2016-11-20 19:24 UTC, merged